### ISSUE TITLE
Cannot create property=parsable / type

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [bmc/sbt-izpack#12]
I have this snippet in `izpack.yml`:

```
packs:
  pack:
    name: Base
    required: yes
    preselected: yes
    description: My pack
    parsable:
      targetFile: $INSTALL_PATH/webIma/config/config.xml
      type: xml
```

and this is the generated error:

```
org.clapper.sbt.izpack.IzPluginException: null; Can't construct a java object for tag:yaml.org,2002:org.clapper.sbt.izpack.IzPackYamlConfig; exception=Cannot create property=packs for JavaBean=org.clapper.sbt.izpack.IzPackYamlConfig@6ee60cdb; Cannot create property=pack for JavaBean=org.clapper.sbt.izpack.Packs@5bbd61d; Cannot create property=parsable for JavaBean=org.clapper.sbt.izpack.Pack@611a4d19; Cannot create property=type for JavaBean=org.clapper.sbt.izpack.Parsable@71f0732f; Unable to find property 'type' on class: org.clapper.sbt.izpack.Parsable
        at org.clapper.sbt.izpack.Util$class.izError(util.scala:87)
        at org.clapper.sbt.izpack.IzPackYamlConfigParser.izError(Yaml.scala:297)
        at org.clapper.sbt.izpack.IzPackYamlConfigParser.parse(Yaml.scala:333)
        at org.clapper.sbt.izpack.IzPack$.org$clapper$sbt$izpack$IzPack$$createXML(IzPack.scala:261)
        at org.clapper.sbt.izpack.IzPack$$anonfun$org$clapper$sbt$izpack$IzPack$$createXMLTask$1.apply(IzPack.scala:237)
        at org.clapper.sbt.izpack.IzPack$$anonfun$org$clapper$sbt$izpack$IzPack$$createXMLTask$1.apply(IzPack.scala:235)
```

It doesn't like the `type: xml`, even though the documentation says it is valid!!!

**Comment by DavidPerezIngeniero** [comment]
By looking at the source code, I've seen that this must be used:

```
parsable:
    targetFile: ...
    parseType: ....
```

instead of:

```
parsable:
    targetFile: ...
    type: ....
```

The code or the doc should be corrected.

**Comment by bmc** [comment]
Corrected. New docs pushed. Thanks.
