### ISSUE TITLE
NullPointerException for missing properties of an action

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [bmc/sbt-izpack#7]
When I forget to specify action properties, I receive this exception:

    java.lang.NullPointerException
        at org.clapper.sbt.izpack.XMLable$$anonfun$seqToXML$1.apply(Yaml.scala:151)
        at org.clapper.sbt.izpack.XMLable$$anonfun$seqToXML$1.apply(Yaml.scala:151)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.clapper.sbt.izpack.XMLable$class.seqToXML(Yaml.scala:151)
        at org.clapper.sbt.izpack.Panel.seqToXML(Yaml.scala:834)
        at org.clapper.sbt.izpack.Panel.sectionToXML(Yaml.scala:861)
        at org.clapper.sbt.izpack.IzPackSection$class.toXML(Yaml.scala:233)
        at org.clapper.sbt.izpack.Panel.toXML(Yaml.scala:834)
        at org.clapper.sbt.izpack.Panels$$anonfun$sectionToXML$5.apply(Yaml.scala:829)
 
instead of a self-explanatory error message.

**Comment by bmc** [comment]
I'm going to make an effort to get to this stuff today.

**Comment by DavidPerezIngeniero** [comment]
Thanks!

**Comment by bmc** [comment]
Would you post some sample YAML that generates this error?

**Comment by bmc** [comment]
Fixed. Will publish and close tomorrow.

**Comment by bmc** [comment]
Published.
